apiVersion: v1
kind: Service
metadata:
  name: suresh-reverse-proxy-nginx
  namespace: suresh-reverse-proxy-nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: suresh-reverse-proxy-nginx
