apiVersion: v1
kind: Service
metadata:
  name: suresh-reverse-proxy-nginx
  namespace: suresh-reverse-proxy-nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
    - port: 443
      name: https 
      targetPort: 443
      protocol: TCP
  selector:
    app: suresh-reverse-proxy-nginx
