apiVersion: apps/v1
kind: Deployment
metadata:
  name: grape-nginx
  namespace: grape-nginx
  labels:
    app: grape-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grape-nginx
  template:
    metadata:
      labels:
        app: grape-nginx
    spec:
      containers:
        - name: grape-nginx
          image: sureshattaluri/grape-suresh-nginx:v0.0.3
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: suresh-docker-registry-creds
