apiVersion: v1
kind: Service
metadata:
  name: grape-nginx
  namespace: grape-nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: grape-nginx
