apiVersion: v1
kind: Service
metadata:
  name: grape-nginx-dev
  namespace: grape-nginx-dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: grape-nginx-dev
