apiVersion: v1
kind: Service
metadata:
  name: apple-nginx-dev
  namespace: apple-nginx-dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: apple-nginx-dev
