apiVersion: v1
kind: Service
metadata:
  name: orange-nginx
  namespace: orange-nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: orange-nginx
