FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY ssl/apple-fullchain.pem /etc/nginx/ssl/apple-fullchain.pem
COPY ssl/apple-privkey.pem /etc/nginx/ssl/apple-privkey.pem
COPY ssl/grape-fullchain.pem /etc/nginx/ssl/grape-fullchain.pem
COPY ssl/grape-privkey.pem /etc/nginx/ssl/grape-privkey.pem
COPY ssl/orange-fullchain.pem /etc/nginx/ssl/orange-fullchain.pem
COPY ssl/orange-privkey.pem /etc/nginx/ssl/orange-privkey.pem
